import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "./provider";
import GlobalHeader from "@/components/header";
import GlobalFooter from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lx-next-starter",
  description: "Generated by create next app",
};
/**
 * 默认布局
 * @param param0 
 * @returns 
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <GlobalHeader />
          {children}
          <GlobalFooter />
        </GlobalProvider>
      </body>
    </html>
  );
}
